
CREATE TABLE IF NOT EXISTS entrenador (
  nick VARCHAR(20) PRIMARY KEY NOT NULL DEFAULT 'Ash Ketpchup',
  level INT(5) NOT NULL,
  exp INT(5) NOT NULL,
  pokeBalls INT(5) NOT NULL,
  superBalls INT(5) NOT NULL,
  ultraBalls INT(5) NOT NULL,
  masterBalls INT(5) NOT NULL,
  region_ini Varchar(10) NULL,
  poke_ini Varchar(3) NULL
  );
  
CREATE TABLE IF NOT EXISTS atrapado(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS equipo(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');

CREATE TABLE IF NOT EXISTS nation(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS kanto(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS johto(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS hoenn(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS sinnoh(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS unova(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS kalos(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS alola(
  num_nation VARCHAR(3) PRIMARY KEY NOT NULL,
  num_region VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  num_evo INT(1) NOT NULL,
  level_evo INT(3) NOT NULL,
  evo VARCHAR(3) NOT NULL,
  level INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  attack INT(4) DEFAULT 5,
  defense INT(4) DEFAULT 5,
  special_attack INT(4) DEFAULT 5,
  special_defense INT(4) DEFAULT 5,
  speed INT(4) DEFAULT 5,
  state VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
