
CREATE TABLE IF NOT EXISTS entrenador (
  nick VARCHAR(20) PRIMARY KEY NOT NULL DEFAULT 'Ash Ketpchup',
  nivel INT(5) NOT NULL,
  exp INT(5) NOT NULL,
  pokeBalls INT(5) NOT NULL,
  superBalls INT(5) NOT NULL,
  ultraBalls INT(5) NOT NULL,
  masterBalls INT(5) NOT NULL,
  region_ini Varchar(10) NULL,
  poke_ini Varchar(3) NULL
  );
  
CREATE TABLE IF NOT EXISTS atrapado(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS equipo(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');

CREATE TABLE IF NOT EXISTS nacional(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS kanto(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS johto(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS hoenn(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS sinnoh(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS teselia(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS kalos(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS alola(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipo_uno VARCHAR(10) NOT NULL,
  tipo_dos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  numero_evolucion INT(1) NOT NULL,
  nivel_evolucion INT(3) NOT NULL,
  evolucion VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  exp INT(3) DEFAULT 0,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  ball VARCHAR(10) DEFAULT 'vacio',
  descripcion VARCHAR(150) DEFAULT 'vacio');
